# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  core-ai-techspike-language-processor:
    build:
      target: development
    image: core-ai-techspike-language-processor-development
    container_name: core-ai-techspike-language-processor-development
    ports:
      - "3001:3000"
      - "9230:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  core-ai-techspike-language-processor-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  core-ai-techspike-language-processor-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

volumes:
  postgres_data:
  azurite_data:
