apiVersion: v2
description: API for management of LLM calls and vector
name: core-ai-techspike-language-processor
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
