environment: production
environmentCode:
name: core-ai-techspike-language-processor
namespace: core-ai
workstream: core-ai
image: core-ai-techspike-language-processor

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: core-ai-techspike-language-processor-config-map

containerSecret:
  name: core-ai-techspike-language-processor-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
