{{- include "ffc-helm-library.container-secret" (list . "core-ai-techspike-language-processor.container-secret") -}}
{{- define "core-ai-techspike-language-processor.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
